Removing VINTF secure clock
Fixup :
Conflicting FqInstance: ISecureClock/default (@1) (from /vendor/etc/vintf/manifest.xml) vs. ISecureClock/default (@1) (from /vendor/etc/vintf/manifest/android.hardware.security.secureclock-service.xml). Check whether or not multiple modules providing the same HAL are installed.
getDeviceHalManifest: Reading VINTF information.
Sysprop ro.boot.product.vendor.sku=
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest.xml': OK
List 'out/target/product/ceres/vendor/etc/vintf/manifest/': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.secureclock-service.xml': OK
getDeviceHalManifest: status from fetching VINTF information: -2147483648
getDeviceHalManifest: -2147483648 VINTF parse error: Cannot add manifest fragment /vendor/etc/vintf/manifest/android.hardware.security.secureclock-service.xml: HAL "android.hardware.security.secureclock" has a conflict: Conflicting FqInstance: ISecureClock/default (@1) (from /vendor/etc/vintf/manifest.xml) vs. ISecureClock/default (@1) (from /vendor/etc/vintf/manifest/android.hardware.security.secureclock-service.xml). Check whether or not multiple modules providing the same HAL are installed.
Unable to print HALs from new FCMs: no device HAL manifest.
ERROR: No such device: No device manifest file from device or from update package
No device manifest.
No device HAL manifest
Missing device manifest.: No such file or directory: No such device