Added    <hal format="aidl">         <name>android.hardware.security.secureclock</name>         <fqname>ISecureClock/default</fqname>     </hal>
fixup :    conflict: Conflicting FqInstance: ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest.xml) vs. ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml). Check whether or not multiple modules providing the same HAL are installed.
Cannot fetch device manifest to determine target FCM version to filter framework manifest HALs properly. Treating as infinitely old device.
getFrameworkHalManifest: Successfully processed VINTF information
getDeviceHalManifest: Reading VINTF information.
Sysprop ro.boot.product.vendor.sku=
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest.xml': OK
List 'out/target/product/ceres/vendor/etc/vintf/manifest/': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.secureclock-service.xml': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml': OK
getDeviceHalManifest: status from fetching VINTF information: -2147483648
getDeviceHalManifest: -2147483648 VINTF parse error: Cannot add manifest fragment /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml: HAL "android.hardware.security.sharedsecret" has a conflict: Conflicting FqInstance: ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest.xml) vs. ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml). Check whether or not multiple modules providing the same HAL are installed.
getDeviceHalManifest: Reading VINTF information.
Sysprop ro.boot.product.vendor.sku=
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest.xml': OK
List 'out/target/product/ceres/vendor/etc/vintf/manifest/': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.secureclock-service.xml': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml': OK
getDeviceHalManifest: status from fetching VINTF information: -2147483648
getDeviceHalManifest: -2147483648 VINTF parse error: Cannot add manifest fragment /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml: HAL "android.hardware.security.sharedsecret" has a conflict: Conflicting FqInstance: ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest.xml) vs. ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml). Check whether or not multiple modules providing the same HAL are installed.
fetched kernel level from RuntimeInfo ''
getDeviceHalManifest: Reading VINTF information.
Sysprop ro.boot.product.vendor.sku=
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest.xml': OK
List 'out/target/product/ceres/vendor/etc/vintf/manifest/': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.secureclock-service.xml': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml': OK
getDeviceHalManifest: status from fetching VINTF information: -2147483648
getDeviceHalManifest: -2147483648 VINTF parse error: Cannot add manifest fragment /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml: HAL "android.hardware.security.sharedsecret" has a conflict: Conflicting FqInstance: ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest.xml) vs. ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml). Check whether or not multiple modules providing the same HAL are installed.
getKernelLevel: Both device manifest and kernel release do not specify kernel FCM version.
getFrameworkCompatibilityMatrix: Reading VINTF information.
List 'out/target/product/ceres/system/etc/vintf/': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.8.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/manifest.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.202404.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.device.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.5.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.6.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.7.xml': OK
List 'out/target/product/ceres/system_ext/etc/vintf/': OK
Fetch 'out/target/product/ceres/system_ext/etc/vintf/manifest.xml': OK
List 'out/target/product/ceres/product/etc/vintf/': NAME_NOT_FOUND
getFrameworkCompatibilityMatrix: Successfully processed VINTF information
getDeviceCompatibilityMatrix: Reading VINTF information.
Fetch 'out/target/product/ceres/vendor/etc/vintf/compatibility_matrix.xml': OK
getDeviceCompatibilityMatrix: Successfully processed VINTF information
fetched kernel version 4.19.191
read kernel configs from out/target/product/ceres/obj/PACKAGING/check_vintf_all_intermediates/kernel_configs.txt
List 'out/target/product/ceres/system/etc/vintf/': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.8.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/manifest.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.202404.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.device.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.5.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.6.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.7.xml': OK
List 'out/target/product/ceres/system_ext/etc/vintf/': OK
Fetch 'out/target/product/ceres/system_ext/etc/vintf/manifest.xml': OK
List 'out/target/product/ceres/product/etc/vintf/': NAME_NOT_FOUND
getDeviceHalManifest: Reading VINTF information.
Sysprop ro.boot.product.vendor.sku=
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest.xml': OK
List 'out/target/product/ceres/vendor/etc/vintf/manifest/': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.secureclock-service.xml': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml': OK
getDeviceHalManifest: status from fetching VINTF information: -2147483648
getDeviceHalManifest: -2147483648 VINTF parse error: Cannot add manifest fragment /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml: HAL "android.hardware.security.sharedsecret" has a conflict: Conflicting FqInstance: ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest.xml) vs. ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml). Check whether or not multiple modules providing the same HAL are installed.
List 'out/target/product/ceres/system/etc/vintf/': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.8.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/manifest.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.202404.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.device.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.5.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.6.xml': OK
Fetch 'out/target/product/ceres/system/etc/vintf/compatibility_matrix.7.xml': OK
List 'out/target/product/ceres/system_ext/etc/vintf/': OK
Fetch 'out/target/product/ceres/system_ext/etc/vintf/manifest.xml': OK
List 'out/target/product/ceres/product/etc/vintf/': NAME_NOT_FOUND
getDeviceHalManifest: Reading VINTF information.
Sysprop ro.boot.product.vendor.sku=
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest.xml': OK
List 'out/target/product/ceres/vendor/etc/vintf/manifest/': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.secureclock-service.xml': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml': OK
getDeviceHalManifest: status from fetching VINTF information: -2147483648
getDeviceHalManifest: -2147483648 VINTF parse error: Cannot add manifest fragment /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml: HAL "android.hardware.security.sharedsecret" has a conflict: Conflicting FqInstance: ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest.xml) vs. ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml). Check whether or not multiple modules providing the same HAL are installed.
getDeviceHalManifest: Reading VINTF information.
Sysprop ro.boot.product.vendor.sku=
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest.xml': OK
List 'out/target/product/ceres/vendor/etc/vintf/manifest/': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.secureclock-service.xml': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml': OK
getDeviceHalManifest: status from fetching VINTF information: -2147483648
getDeviceHalManifest: -2147483648 VINTF parse error: Cannot add manifest fragment /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml: HAL "android.hardware.security.sharedsecret" has a conflict: Conflicting FqInstance: ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest.xml) vs. ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml). Check whether or not multiple modules providing the same HAL are installed.
getKernelLevel: Both device manifest and kernel release do not specify kernel FCM version.
getDeviceHalManifest: Reading VINTF information.
Sysprop ro.boot.product.vendor.sku=
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest.xml': OK
List 'out/target/product/ceres/vendor/etc/vintf/manifest/': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.secureclock-service.xml': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml': OK
getDeviceHalManifest: status from fetching VINTF information: -2147483648
getDeviceHalManifest: -2147483648 VINTF parse error: Cannot add manifest fragment /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml: HAL "android.hardware.security.sharedsecret" has a conflict: Conflicting FqInstance: ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest.xml) vs. ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml). Check whether or not multiple modules providing the same HAL are installed.
getDeviceHalManifest: Reading VINTF information.
Sysprop ro.boot.product.vendor.sku=
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest.xml': OK
List 'out/target/product/ceres/vendor/etc/vintf/manifest/': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.secureclock-service.xml': OK
Fetch 'out/target/product/ceres/vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml': OK
getDeviceHalManifest: status from fetching VINTF information: -2147483648
getDeviceHalManifest: -2147483648 VINTF parse error: Cannot add manifest fragment /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml: HAL "android.hardware.security.sharedsecret" has a conflict: Conflicting FqInstance: ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest.xml) vs. ISharedSecret/default (@1) (from /vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.xml). Check whether or not multiple modules providing the same HAL are installed.
Unable to print HALs from new FCMs: no device HAL manifest.
ERROR: No such device: No device manifest file from device or from update package
No device manifest.
No device HAL manifest
Missing device manifest.: No such file or directory: No such device